### PR TITLE
added @functools.wraps(run_func) to task_complete_check_wrapper

### PR DESCRIPTION
**Pull request by mski-iksm**
I've added @functools.wraps not to change wrapped function's name.

### CODE REVIEW

**Comment by Hi-king** [comment]
LGTM!

**Comment by yokomotod** [comment]
@mski-iksm Can we have any kind of unit test ?

I'm not sure what problem happen if decorate function name changed. (but yes, sounds problem 😅

**Comment by mski-iksm** [comment]
@yokomotod 
This PR is not to fix any bug, instead it is for readability.

So there is no concrete problem case, and therefore I think no test is required.

**Comment by yokomotod** [comment]
I see, then I agree to not have unit test for `@functools.wraps` functionality itself !

and +1 for using `@functools.wraps` habit

**Review by yokomotod — APPROVED** [review]

**Review by Hi-king — APPROVED** [review]

**Pull request merged**
