### PR TITLE
[docs] Fix typo: templete -> template

### PR DESCRIPTION
**Pull request by pn11**
Fix typo (templete -> template) to be consistent with https://github.com/m3dev/cookiecutter-gokart/issues/4.

### CODE REVIEW

**Comment by hirosassa** [comment]
@pn11 Thank you for your contribution! Looks good!

**Comment by hirosassa** [comment]
@pn11 CI is failed but it doesn't come from your change.

I'm now fixing the problem in https://github.com/m3dev/gokart/pull/302 .
I'll ask you to take the changes of #302 in this branch after the PR is merged.
Please wait a moment.

**Comment by hirosassa** [comment]
@pn11 #302 is merged. Please rebase current master branch into this PR.

**Comment by pn11** [comment]
@hirosassa Thank you. I rebased master.

**Comment by hirosassa** [comment]
@pn11 Thank you for your contribution!

**Review by hirosassa — APPROVED** [review]

**Pull request merged**
