### PR TITLE
Added example notebook

### PR DESCRIPTION
**Pull request by mski-iksm**
I've added a notebook of very basic usages of gokat.build().

Issue: https://github.com/m3dev/gokart/issues/225

### CODE REVIEW

**Comment by mski-iksm** [comment]
@hirosassa @vaaaaanquish @Hi-king 
Please review this PR.

**Review by hirosassa — APPROVED** [review]
LGTM

**Comment by vaaaaanquish** [comment]
It would be better to indicate the version.
```
!pip list | grep gokart
```

**Review by vaaaaanquish — APPROVED** [review]

**Comment by mski-iksm** [comment]
@hirosassa @vaaaaanquish I've applied the suggestion. This PR is ready for merge.

**Comment by hirosassa** [comment]
Thanks for your contribution!

**Pull request merged**
