### PR TITLE
Specific load

### LINKED ISSUE #189: Easy load specific data
```
class A(gokart.TaskOnKart):
    task = gokart.TaskInstanceParameter()

    def run(self):
        a = self.load()
```

This is uniquely determined, but Not implemented.

### PR DESCRIPTION
**Pull request by vaaaaanquish**
fix #189

### CODE REVIEW

**Comment by vaaaaanquish** [comment]
@Hi-king @hirosassa Please review

**Comment by mski-iksm** [comment]
@vaaaaanquish 
[IMO] I believe this PR allows `self.load()` without setting any parameter.

However, I thought we should select target name explicitly as in the following example. (I think this is possible in the current code)
If not, we have to add parameter to `self.load()` as `self.load('task1')` when we decided to add another `gokart.TaskInstanceParameter()` afterward, which may be difficult to notice.

```
class A(gokart.TaskOnKart):
    task = gokart.TaskInstanceParameter()

    def run(self):
        a = self.load('target')
```

**Comment by vaaaaanquish** [comment]
@mski-iksm Thanks for the good point.

It would be good to add a condition to check if target is in data. 
```
        if isinstance(data, dict) and len(data) == 1 and target in data:
            return list(data.values())[0]
```

**Review by hirosassa — APPROVED** [review]
Looks good!

**Comment by mski-iksm** [comment]
@vaaaaanquish LGTM

**Pull request merged**
