### PR TITLE
fix gokart logger

### PR DESCRIPTION
**Pull request by vaaaaanquish**
We were not doing gokart logging.

Because, Settings written in `core sections` can't be read.  
This is a matter of order.
```
[gokart.run] --> [part of gokart logging] --> [luigi._schedule_and_run(load log.ini)]
```
```
[core]
logging_conf_file=./log.ini
```

We need to load core.logging_conf_file in advance.

### CODE REVIEW

**Comment by vaaaaanquish** [comment]
Resolve https://github.com/m3dev/gokart/pull/98 first :)

**Comment by vaaaaanquish** [comment]
@hirosassa @nishiba Please check PR.
We couldn't see all the logs in gokart. This change will take advantage of logging.ini :)

**Comment by nishiba** [comment]
LGTM!  @hirosassa how do you think?

**Comment by Hi-king** [comment]
LGTM

**Pull request merged**
