### PR TITLE
Feature/add inherits config params

### PR DESCRIPTION
**Pull request by mski-iksm**
Added feature to set task parameter by inheritance.
(This was originally implemented by @e-mon . Thanks!)

You may now set parameter in following decorator.

```python
class MasterConfig(luigi.Config):
    param: str = luigi.Parameter()
    param2: str = luigi.Parameter()

@inherits_config_params(MasterConfig)
class SomeTask(gokart.TaskOnKart):
    param: str = luigi.Parameter()
```

This is useful when setting same parameter to multiple tasks.

Please review.
@Hi-king @e-mon @hirosassa @vaaaaanquish

### CODE REVIEW

**Comment by Hi-king** [comment]
@mski-iksm cool feature! LGTM!

**Review by Hi-king — APPROVED** [review]

**Comment by Hi-king** [comment]
@e-mon @hirosassa  any comments?

**Comment by hirosassa** [comment]
Good feature! LGTM

**Comment by Hi-king** [comment]
@mski-iksm I'll merge this! Thx :)

**Pull request merged**
