### PR TITLE
migrating slack_sdk from slackclient and cleanup

### PR DESCRIPTION
**Pull request by hirosassa**
Slack client version 3 is available and v2 will be deprecated soon.
In this PR, migrating to `slack_sdk` package.

ref: https://slack.dev/python-slack-sdk/v3-migration/

### CODE REVIEW

**Comment by hirosassa** [comment]
@Hi-king @mski-iksm @vaaaaanquish plz review

**Comment by mski-iksm** [comment]
LGTM

**Comment by Hi-king** [comment]
@hirosassa LGTM

**Comment by hirosassa** [comment]
Thanks!

**Pull request merged**
