### PR TITLE
Update documentation for fail_on_empty_dump

### PR DESCRIPTION
**Pull request by yamasakih**
## What I did
- Update documentation for fail_on_empty_dump
(Close to https://github.com/m3dev/gokart/issues/281)

### CODE REVIEW

**Comment by Hi-king** [comment]
@yamasakih Really thanks for fixing the wrong documentation!

LGTM


Anyway, another example to use fail_on_empty_dump in notebook is as follows.

```
    class EmptyTask(gokart.TaskOnKart):
        fail_on_empty_dump: bool = ExplicitBoolParameter(default=False, description='Fail when task dumps empty DF', significant=False) #override TaskOnKart.fail_on_empty_dump
        def run(self):
            df = pd.DataFrame()
            self.dump(df)
```

We can override `fail_on_empty_dump` on any tasks instead of injecting it from conf

**Comment by mski-iksm** [comment]
@yamasakih Thank you for fixing the document!  LGTM!

**Review by Hi-king — APPROVED** [review]

**Comment by Hi-king** [comment]
@yamasakih Thx for your contribution!

**Comment by yamasakih** [comment]
@Hi-king

Thank you for introducing another way.
I thought it was very nice because I thought it was one way to override as you said.

 @mski-iksm 
Thank you for your suggestion!

**Pull request merged**
