### PR TITLE
removed unnecessary parameter and added accept dict

### PR DESCRIPTION
**Pull request by kuri8ive**
responding to #59
remove unnecessary parameter `index=False` at `dump() in JsonFileProcessor`

### CODE REVIEW

**Comment by 6syun9** [comment]
LGTM

**Comment by hirosassa** [comment]
LGTM 👍

**Comment by kuri8ive** [comment]
additional commit about dict support in JsonFileProcessor

**Comment by nishiba** [comment]
LGTM

**Pull request merged**
