### PR TITLE
Generate default target automatically

### PR DESCRIPTION
**Pull request by mpozpnd**
- make Target to have default SingleFileTarget automatically
    - filename is TASK_WORKSPACE_DIRECTORY/{directory(ies)}{file name}/{class name}_{hash}.pkl

### CODE REVIEW

**Comment by vaaaaanquish** [comment]
LGTM

**Comment by mpozpnd** [comment]
I changed the design of patch
here is an example output. please check it, especially if the directory structure and name of the output is appropriate or not
- example task structure
```
.                                                                                                                      
└── karttest
   ├── __init__.py
   ├── data
   │   ├── __init__.py
   │   ├── prepare_data.py  # class DataTask
   │   └── process_data.py  # class ProcessDataTask
   ├── report
   │   ├── __init__.py
   │   └── report_model.py  # class ReportTask
   └── train
       ├── __init__.py
       └── train_model.py  # class TrainTask
```

- output:
```
── resources
    ├── karttest
    │   ├── data
    │   │   ├── prepare_data
    │   │   │   └── DataTask_10f87ddcf3df71d786a023ae5e0bbc98.pkl
    │   │   └── process_data
    │   │       └── ProcessDataTask_08aa2ad6f6ebc05b316052dfd3dc7f41.pkl
    │   ├── report
    │   │   └── report_model
    │   │       └── ReportTask_fffb50ad7e358a72b7c487b8f8537a0e.pkl
    │   └── train
    │       └── train_model
    │           └── TrainTask_edab030d184d77f9f0be964c7514d3bf.pkl
    └── log
```

**Comment by vaaaaanquish** [comment]
I checked successed in module ! great !

**Comment by nishiba** [comment]
LGTM

**Pull request merged**
