### PR TITLE
Release v1.0.0

### PR DESCRIPTION
**Pull request by vaaaaanquish**
#184

### CODE REVIEW

**Comment by Hi-king** [comment]
@vaaaaanquish @hirosassa 
(Just asking)
Is this better way to create this big PR to master?
I think all MRs related to this MR can be merged into master separately.

**Comment by vaaaaanquish** [comment]
@Hi-king Thx.
The major changes are as follows:

- Add running gokart task on interpreter #183
- Fix GCSClient bug #187
- specific load #189
- compress tree info #192

I think each one is small and isolated.
(And the desire to make 1.0.0 a grand success 🤫 )

But your point is correct, so let's consider it.

**Review by hirosassa — APPROVED** [review]
Can't wait for it!

**Comment by vaaaaanquish** [comment]
I'm too excited to sleep!!

**Pull request merged**
