### PR TITLE
add file path in task log

### PR DESCRIPTION
**Pull request by 6syun9**
https://github.com/m3dev/gokart/issues/72

### CODE REVIEW

**Comment by 6syun9** [comment]
@nishiba please check PR!

**Comment by nishiba** [comment]
@6syun9 Why didn't you change `_dump_task_log` on https://github.com/m3dev/gokart/blob/master/gokart/task.py#L233

In the function, we can get all target instances and  extract file paths like this:
```
self.task_log['file_path'] = [target.path() for target in flatten(self.output())]
```

**Comment by 6syun9** [comment]
@nishiba 
result is different.
- PR result
```
 {'s3:/hoge/data/piyo_qawsedrf....pkl',
  's3:/hoge/log/task_log/piyo.pkl',
  's3:/hoge/log/task_params/piyo.pkl',
  's3:/hoge/log/processing_time/piyo.pkl'}
```
- flatten(target.output()) resulet
```
['s3:/hoge/data/piyo_qawsedrf....pkl']
```
Nishiba's result is enough, so I will chenge code. Thank you.

**Comment by nishiba** [comment]
LGTM!

**Pull request merged**
