### PR TITLE
fix bugs #196

### PR DESCRIPTION
**Pull request by vaaaaanquish**
Sorry, I've created a serious bug here.
luigi's `List` is `tuple`...I'd forgotten. https://github.com/m3dev/gokart/pull/196

### CODE REVIEW

**Comment by vaaaaanquish** [comment]
@Hi-king @hirosassa sorry

**Review by hirosassa — APPROVED** [review]
LGTM! Thanks!

**Comment by mski-iksm** [comment]
@vaaaaanquish 
LGTM!

**Comment by Hi-king** [comment]
> luigi's List is tuple
Yes. Very frequent cases :)
And sorry for my overlooking in the past review.

**Review by Hi-king — APPROVED** [review]

**Pull request merged**
