### PR TITLE
add github actions workflow

### PR DESCRIPTION
**Pull request by hirosassa**
# What I did
- remove travis dependencies
- add github action workflow
  - add lint by yapf
- format some files by yapf

### CODE REVIEW

**Comment by hirosassa** [comment]
@nishiba @vaaaaanquish 
I add github actions for CI. Since there's an problem about secret variables, we still use travis for uploading PyPI.

**Comment by vaaaaanquish** [comment]
Looks good! Make a request to GitHub!

**Comment by vaaaaanquish** [comment]
https://github.com/m3dev/gokart/issues/108

**Comment by hirosassa** [comment]
close this PR coz of financial cost!

**Pull request closed without merging**
